# Generated by Django 2.1 on 2018-08-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('ARS', 'Argentina Peso'), ('BRL', 'Brazil Real'), ('CLP', 'Chilean Peso'), ('USD', 'United States Dollar'), ('UYU', 'Uruguay Peso')], max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.CharField(blank=True, choices=[('5', 'Excellent'), ('4', 'Really good'), ('3', 'Good'), ('2', 'Poor'), ('1', 'Awful')], max_length=20, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, choices=[('5', 'Excellent'), ('4', 'Really good'), ('3', 'Good'), ('2', 'Poor'), ('1', 'Awful')], max_length=20, null=True, verbose_name='Quality'),
        ),
    ]
