# Generated by Django 2.1 on 2018-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180825_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='posted',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default=False, max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default=False, max_length=10, verbose_name='Status'),
        ),
    ]
