# Generated by Django 2.1 on 2018-09-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180919_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Published'), ('0', 'Draft')], default='Draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Published'), ('0', 'Draft')], default='Draft', max_length=10, verbose_name='Status'),
        ),
    ]
