# Generated by Django 2.1 on 2018-09-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180919_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='co',
            field=models.BooleanField(default=False, verbose_name='Comments replied'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ig',
            field=models.BooleanField(default=False, verbose_name='Published on Instagram'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='Draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='Draft', max_length=10, verbose_name='Status'),
        ),
    ]
