# Generated by Django 2.1 on 2018-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20180924_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Hashtags'),
        ),
    ]
