# Generated by Django 2.1 on 2018-09-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20180924_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short',
        ),
    ]
