# Generated by Django 2.1 on 2018-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_post_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hashtags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=300, verbose_name='Tags'),
        ),
    ]
