# Generated by Django 2.1 on 2018-09-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20180924_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='ig',
            field=models.BooleanField(default=False, verbose_name='Published on IG'),
        ),
    ]
